# SVM  
*   https://www.youtube.com/watch?v=_YPScrckx28
*   https://en.wikipedia.org/wiki/Support_vector_machine
*   https://scikit-learn.org/1.5/modules/svm.html

Metoda: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html#examples-using-sklearn-model-selection-gridsearchcv

Dane do analizy: https://www.kaggle.com/datasets/raminhuseyn/hr-analytics-data-set

Zadanie: zaczytać dane i zbudować model: tree, random forest, logistic, kNN

In [ ]:
!kaggle datasets download -d raminhuseyn/hr-analytics-data-set

Dataset URL: https://www.kaggle.com/datasets/raminhuseyn/hr-analytics-data-set
License(s): other
hr-analytics-data-set.zip: Skipping, found more recently modified local copy (use --force to force download)

In [ ]:
!unzip hr-analytics-data-set.zip

Archive:  hr-analytics-data-set.zip
replace HR_capstone_dataset.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: HR_capstone_dataset.csv

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('HR_capstone_dataset.csv')

In [ ]:
df.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low

In [ ]:
df['left'].mean()

0.2380825388359224

In [ ]:
df['left'].value_counts()

left
0    11428
1     3571
Name: count, dtype: int64

In [ ]:
df_dummy = pd.get_dummies(df, drop_first=True)
df_dummy

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department_RandD,Department_accounting,Department_hr,Department_management,Department_marketing,Department_product_mng,Department_sales,Department_support,Department_technical,salary_low,salary_medium
0,0.38,0.53,2,157,3,0,1,0,False,False,False,False,False,False,True,False,False,True,False
1,0.80,0.86,5,262,6,0,1,0,False,False,False,False,False,False,True,False,False,False,True
2,0.11,0.88,7,272,4,0,1,0,False,False,False,False,False,False,True,False,False,False,True
3,0.72,0.87,5,223,5,0,1,0,False,False,False,False,False,False,True,False,False,True,False
4,0.37,0.52,2,159,3,0,1,0,False,False,False,False,False,False,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14994,0.40,0.57,2,151,3,0,1,0,False,False,False,False,False,False,False,True,False,True,False
14995,0.37,0.48,2,160,3,0,1,0,False,False,False,False,False,False,False,True,False,True,False
14996,0.37,0.53,2,143,3,0,1,0,False,False,False,False,False,False,False,True,False,True,False
14997,0.11,0.96,6,280,4,0,1,0,False,False,False,False,False,False,False,True,False,True,False
14998,0.37,0.52,2,158,3,0,1,0,False,False,False,False,False,False,False,True,False,True,False

In [ ]:
from sklearn.model_selection import train_test_split

X = df_dummy.drop(columns=['left'], axis=1)
y = df_dummy['left']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.metrics import classification_report

## Zadanie: zbudować model korzystając z SVM oraz grid search

In [ ]:
from sklearn import svm

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
svc = svm.SVC(random_state=0, )

In [ ]:
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
svc = svm.SVC(random_state=0)
clf = GridSearchCV(svc, parameters)
clf.fit(X_train, y_train)

GridSearchCV(estimator=SVC(random_state=0),
             param_grid={'C': [1, 10], 'kernel': ('linear', 'rbf')})

In [ ]:
clf.best_paramms_

{'C': 10, 'kernel': 'rbf'}

In [ ]:
clf_sel = clf.best_estimator_

In [ ]:
svc = svm.SVC(C=10, kernel='rbf')  #  clf_sel
svc.fit(X_train, y_train)

SVC(C=10)

In [ ]:
print(classification_report(y_test, svc.predict(X_test)))

              precision    recall  f1-score   support

           0       0.98      0.97      0.97      3462
           1       0.90      0.92      0.91      1038

    accuracy                           0.96      4500
   macro avg       0.94      0.94      0.94      4500
weighted avg       0.96      0.96      0.96      4500

In [ ]:
print(classification_report(y_train, svc.predict(X_train)))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98      7966
           1       0.94      0.93      0.94      2533

    accuracy                           0.97     10499
   macro avg       0.96      0.96      0.96     10499
weighted avg       0.97      0.97      0.97     10499